spring:
  application:
    name: order-service
  mvc:
    apiversion:
      use:
        path-segment: 0
      supported: v1
      default: v1
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    properties:
      auto:
        register:
          schemas: true
    producer:
      acks: all
      retries: 50
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        retry:
          backoff:
            ms: 250
        schema:
          registry:
            url: ${KAFKA_SCHEMA_REGISTRY:http://localhost:8081}
        specific:
          avro:
            reader: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

viacep:
  api:
    base-url: https://viacep.com.br/ws

aws:
  dynamo:
    service-endpoint: ${SERVICE_ENDPOINT:http://localhost:4566}
    region: ${REGION:us-east-1}
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}

springdoc:
  api-docs:
    path: /v1/docs
    resolve-schema-properties: true
  swagger-ui:
    path: /v1/docs/ui
    operationsSorter: method

kafka:
  topics:
    order-created: order.created
    order-cancelled: order.cancelled
